name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy-dev:
        description: 'Deploy to Development?'
        type: boolean
        default: true
      deploy-preprod:
        description: 'Deploy to Preproduction?'
        type: boolean
        default: false
      deploy-prod:
        description: 'Deploy to Production?'
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  # Run the centralized DevSecOps Go pipeline template (updated node version actions)
  pipeline:
    uses: mashurimansur/pipeline-template/.github/workflows/pipeline-devsecops-go.yml@master
    with:
      go-version: '1.25.12'
      image-name: 'go-k8s-deployment'
      release-name: 'go-k8s-deployment'
      chart-path: './helm/go-k8s-deployment'
      dev-namespace: 'dev'
      preprod-namespace: 'preprod'
      prod-namespace: 'production'
      deploy-dev: ${{ github.event_name == 'push' || inputs.deploy-dev == true }}
      deploy-preprod: ${{ github.event_name != 'push' && inputs.deploy-preprod == true }}
      deploy-prod: ${{ github.event_name != 'push' && inputs.deploy-prod == true }}
    secrets: inherit
